pipeline:
  test-prep:
    image: mongo
    commands:
    - mongoimport --db test_db --collection widgets --type json --file seed.json --jsonArray
  test:
    image: mongo
    commands:
    - mongo --eval "db.widgets.find({});" test_db
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: ci

services:
  mongo:
    image: mongo
